"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Compass, MessageSquare, Sparkles, Zap } from "lucide-react";
import { useApp, useHydrated } from "@/lib/store/app";
import { useSession } from "@/lib/store/session";
import { Avatar } from "@/components/ui/avatar";
import { CardSkeleton } from "@/components/ui/skeleton";
import { StatusPill } from "@/components/ui/status-pill";
import { Button } from "@/components/ui/button";
import { companyById } from "@/lib/seed";
import { daysAgo } from "@/lib/format";
import { fetchProfileNames } from "@/lib/sync";

export default function MessagesPage() {
  const hydrated = useHydrated();
  const userId = useSession((s) => s.userId);
  const role = useSession((s) => s.role);
  const isDemo = useSession((s) => s.isDemo);
  const { gigs, messages, creators } = useApp();
  const [profileNames, setProfileNames] = useState<Record<string, { name: string; hue: number }>>({});

  const myGigs = userId ? gigs.filter((g) =>
    role === "creator" ? g.creatorId === userId : g.companyId === userId,
  ) : [];
  const companyIds = Array.from(new Set(myGigs.map((g) => g.companyId)));
  const companyIdsKey = companyIds.join(",");
  const threads = myGigs
    .map((g) => ({
      gig: g,
      last: [...messages].reverse().find((m) => m.gigId === g.id),
    }))
    .filter((t) => t.last)
    .sort((a, b) => (b.last!.createdAt ?? "").localeCompare(a.last!.createdAt ?? ""));

  useEffect(() => {
    if (isDemo || role !== "creator" || myGigs.length === 0) return;
    let cancelled = false;
    void fetchProfileNames(companyIds).then((names) => {
      if (!cancelled) setProfileNames(names);
    });
    return () => {
      cancelled = true;
    };
  }, [companyIdsKey, isDemo, role]);

  if (!hydrated || !userId) return <CardSkeleton />;

  return (
    <div className="space-y-4">
      <div>
        <h1 className="font-serif text-4xl sm:text-5xl font-extrabold leading-[0.95]">Messages</h1>
        <p className="mt-2 text-sm font-bold text-text-secondary">
          Every negotiation stays on-platform — offers, scripts, and files in one thread.
        </p>
      </div>

      {threads.length === 0 ? (
        <div className="mt-2 space-y-4">
          {/* Feature callouts */}
          <div className="grid gap-3 sm:grid-cols-3">
            {[
              {
                icon: Zap,
                color: "#f2a3df",
                title: "Instant offers",
                body: "Brands send structured offer cards — price, deliverables, usage rights — all in one tap.",
              },
              {
                icon: Sparkles,
                color: "#a8d98a",
                title: "AI scripts in-thread",
                body: "Script cards generated by the AI engine land right here, attached to the gig.",
              },
              {
                icon: MessageSquare,
                color: "#faf6ef",
                title: "One thread per gig",
                body: "Files, revisions, payment status, and chat — no email, no DMs, no lost briefs.",
              },
            ].map(({ icon: Icon, color, title, body }) => (
              <div
                key={title}
                className="rounded-[20px] border-2 border-ink bg-surface p-5"
              >
                <span
                  className="mb-3 flex h-10 w-10 items-center justify-center rounded-full"
                  style={{ background: color }}
                >
                  <Icon className="h-5 w-5 text-ink" />
                </span>
                <p className="font-serif text-base font-extrabold">{title}</p>
                <p className="mt-1.5 text-[13px] font-medium leading-relaxed text-text-secondary">{body}</p>
              </div>
            ))}
          </div>

          {/* CTA */}
          <div className="flex flex-col items-center gap-4 rounded-[24px] border-[3px] border-ink bg-ink py-10 text-center text-[#faf6ef]">
            <div className="flex h-16 w-16 items-center justify-center rounded-full bg-[#f2a3df]">
              <MessageSquare className="h-8 w-8 text-ink" />
            </div>
            <div>
              <p className="font-serif text-2xl font-extrabold">No conversations yet</p>
              <p className="mt-1.5 max-w-xs text-sm font-medium text-[#faf6ef]/60">
                Apply to an opportunity to start your first brand conversation — it opens automatically.
              </p>
            </div>
            <Button asChild className="bg-[#f2a3df] text-ink hover:bg-[#f2a3df]/90">
              <Link href="/dashboard/opportunities">
                <Compass className="h-4 w-4" /> Browse opportunities
              </Link>
            </Button>
          </div>
        </div>
      ) : (
        <div className="overflow-hidden rounded-[16px] border-2 border-ink bg-surface shadow-[3px_3px_0_0_#101805]">
          {threads.map(({ gig, last }) => {
            const other =
              role === "creator"
                ? {
                    name: companyById(gig.companyId)?.name ?? profileNames[gig.companyId]?.name ?? "Brand",
                    hue: companyById(gig.companyId)?.logoHue ?? profileNames[gig.companyId]?.hue ?? 285,
                    src: undefined,
                  }
                : (() => {
                    const c = creators.find((c) => c.id === gig.creatorId);
                    return { name: c?.name ?? "Creator", hue: c?.avatarHue ?? 0, src: c?.avatarUrl };
                  })();
            const preview =
              last!.kind === "text"
                ? last!.text
                : last!.kind === "offer"
                  ? "📋 Offer card"
                  : last!.kind === "script"
                    ? "✨ Script card"
                    : `📎 ${last!.attachmentName}`;
            return (
              <Link
                key={gig.id}
                href={`/gig/${gig.id}`}
                className="flex items-center gap-3 border-b-2 border-ink/10 px-4 py-4 transition-colors last:border-0 hover:bg-surface-2/60"
              >
                <Avatar name={other.name} hue={other.hue} src={other.src} size="md" />
                <div className="min-w-0 flex-1">
                  <div className="flex items-baseline justify-between gap-2">
                    <p className="truncate text-sm font-bold">{other.name}</p>
                    <span className="num shrink-0 text-[11px] text-text-tertiary">{daysAgo(last!.createdAt)}</span>
                  </div>
                  <p className="truncate text-[13px] font-medium text-text-secondary">{preview}</p>
                  <p className="mt-0.5 truncate text-xs font-medium text-text-tertiary">{gig.title}</p>
                </div>
                <StatusPill status={gig.status} />
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
